name: Generate Pydantic Models from AVSC

on:
  push:
    paths:
      - '**/*.avsc'  # Run this workflow when .avsc files are changed

jobs:
  generate-pydantic-models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install pydantic-avro
        run: pip install pydantic-avro
      
      - name: Generate Pydantic models
        run: |
          for file in $(find . -name '*.avsc'); do
            model_name=$(basename "$file" .avsc)
            namespace_dir=$(jq -r '.namespace' "$file" | tr '.' '/')
            mkdir -p "models/$namespace_dir"
            pydantic-avro avro_to_pydantic --asvc "$file" --output "models/${namespace_dir}/${model_name}.py"
          done
      
      - name: Commit and Push Generated Models
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-generate Pydantic models from AVSC"
